version: '3.7'

services:
  app:
    build: ./shortener
    command: uvicorn main:app --reload --workers 1 --host localhost --port 8000
    volumes:
      - ./src/:/usr/src/shortener/
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:September23@localhost:5432/shortener_db
  db:
    image: postgres:12.1-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    environment:
      - DB_USERNAME
      - DB_PASSWORD
      - DB_NAME
      - DB_HOST
      - DB_PORT
    ports:
      - "5432"
