version: '3.7'

services:
  web:
    build: ./src
    command: uvicorn shortener.main:app --reload --workers 1 --host localhost --port 8000
    volumes:
      - ./src/:/usr/src/shortener/
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://hello_fastapi:hello_fastapi@db/hello_fastapi_dev

  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  volumes:
    postgres_data:

